### ISSUE TITLE
Possible interaction with Auto Tab Discard

### ISSUE THREAD

**Issue by DDzwiedziu** [glkx/digital-detox#9]
_What happened?_

When I've installed DD it's first action was to load all discarded trough ATD Old Reddit tabs. Which in turn slowed down Fx significantly (i had overall 300 tabs open). After being loaded with a message that DD happily stopped a "impulse" visit tabs are loaded again. And after a while I see the stopped tabs loading again. Also when I've paused DD the tabs are loaded once more, just to their original URL (which at leasts will save me some tab loss, when I uninstall DD).

_What I expected?_

For DD not touch discarded tabs, until explicitly loaded.

_Versions_

Firefox: 87
Auto Tab Discard: 0.4.2
Digital Detox: 1.5.9

**Comment by glkx** [comment]
Restoring of tabs has been improved. Only tabs in memory are restored when DD is disabled. Should improve performance significantly with a lot of open tabs =)
